#
# This reads modbus values from an Automation Direct GS20 VFD
#
# This isn't used for control, only for device feedback
#

[MB2HAL_INIT]
INIT_DEBUG = 2
TOTAL_TRANSACTIONS = 1
HAL_MODULE_NAME = gs20-vfd
VERSION=1.1
SLOWDOWN=0.05

[TRANSACTION_00]
# set P09.04 to 12 (8/N/1 RTU)
LINK_TYPE=serial
SERIAL_PORT=/dev/ttyUSB0
SERIAL_BAUD=9600
SERIAL_BITS=8
SERIAL_PARITY=none
SERIAL_STOP=1
MB_SLAVE_ID=1
# 0x2102 = 8450
FIRST_ELEMENT=8450
PIN_NAMES=raw_freq_cmd,raw_output_freq,raw_output_current,raw_bus_voltage,raw_output_voltage,ignored_7,ignored_8,ignored_9,raw_power_factor_angle,raw_output_torque,raw_motor_speed
MB_TX_CODE=fnct_03_read_holding_registers

