component rateknob "Handles a rotary encoder with push button to select between adjusting two items";
pin in s32 in;
pin in bit button;
pin out s32 out1;
pin out s32 out2;
pin out bit out1_selected;
pin out bit out2_selected;
pin out bit reset;
variable int last_button;
variable int counter = 1;
function _;
license "GPL"; // indicates GPL v2 or later
;;
if (button && !last_button)
{
	counter = (counter + 1) % 3;
	reset = 1;
} else {
	reset = 0;
}


out1_selected = 0;
out2_selected = 0;

if (counter == 0 || counter == 2)
{
	out1_selected = 1;
	out1 = in;
}

if (counter == 1 || counter == 2)
{
	out2_selected = 1;
	out2 = in;
}

last_button = button;
